### ISSUE TITLE
Question: Are custom checkbox groups a valid use case?

### ISSUE THREAD

**Issue by tansongyang** [paypal/downshift#160]
First of all, thanks for the great work on this component.

I really like the flexibility downshift provides, particularly that it manages state for you while letting you decide what to render. Although this isn't an official use case, I found that downshift works well for implementing a custom checkbox group. I'm not using a "real" `<input type="checkbox" />`, which is why I couldn't use something like [react-checkbox-group](https://github.com/ziad-saab/react-checkbox-group)

[Example](https://codesandbox.io/s/7n15y1z3x)

Is there any reason not to use downshift for this?

**Comment by kentcdodds** [comment]
Haha! I love it! Not really what downshift was built for, so downshift includes some code you don't need, but it does the job and does it pretty well I think!

Just don't forget to make it accessible! I can't select items with the keyboard and I get no indication which item has focus :wink:

I'm glad you like downshift :smile:

**Comment by tansongyang** [comment]
@kentcdodds After our discussion yesterday, I tried to do the same thing with a real `<input type="checkbox" />`. It seemed to work, except for a small issue.

You can see it (here)[https://codesandbox.io/s/vmkx9v6185]. Basically, if you comment out the `setTimeout`, clicking on a checkbox will cause the state to update, but the checkbox will not rerender. You have to have a second state update (e.g. mousing over an item) before the checkbox rerenders. Using `setTimeout` to trigger the second state change seems to work.

I'm not posting this as a real issue because I understand that this technically isn't what downshift was intended for. However, I thought I would share with you in case you were interested.

**Comment by jole78** [comment]
@tansongyang @kentcdodds  OMG...I am building something similar...dropdown that shows a bunch of checkboxes (like a list of checkboxes with choices...a multiselect with checkboxes basically) and I couldn't figure out why the checkboxes didn't update when I clicked them but when I moused over them they'd update. Is there a reason why this doesn't work with checkboxes and is there a "better fix" than the setTimeOut hack?? Anyways...also glad for downshift and love every bit of it otherwise!
