### ISSUE TITLE
Decide whether to initially show a full list of items or only a subset

### ISSUE THREAD

**Issue by slavab89** [paypal/downshift#162]
I've started using this great project and so far its really great =] so thanks for it!

One of the things that i've noticed is that there is no real distinction between the `selectedItem` and `inputValue`.
Lets assume that the `items` array is a simple string array.
Once the component creates it sets the `inputValue` to be the `selectedItem`. Once the component calls a `reset` function, same thing happens.
Because of this, its not really possible to decide wether we should filter the items, show everything etc.

Take as an example `react-select` and consider the following flow:
1. Go into the page - the select will be empty without any data.
2. Once clicked it will open the menu with all the items (the `inputValue` is empty/null)
3. Choose some item - Menu will close and selected item will be displayed in the select box
4. Click on the field again - **A menu with all the options will be openned**. In downshift, the menu will only contain 1 item, the selected one.
5. Start writing something - the items menu will be filtered accordingly. In downshift i'll have to delete the whole input to see the full list of items.

In my opinion, step 4,5 make it a lot more intuitive to work with the select box.
In order to implement it on my end i'll have to take full control over the `inputValue` and its events (`onChange`, `onBlur` etc.). I'll set inputValue to be `null` as long as i'm didnt write anything and reset it to `null` once the input blurs.
The filtering of items would return everyone because `inputValue` is `null` but the actual value that will show in the input box will be the `selectedItem` IF the input value is null (didnt enter text yet)
 ```js
let _value = inputValue || '';
if (inputValue === null && fullSelectedItem) {
  _value = fullSelectedItem;
}
```

Using `downshift: "1.0.2"`

**Comment by kentcdodds** [comment]
Hi @slavab89!

Glad you're using downshift! I hope it's helpful to you :)

> there is no real distinction between the `selectedItem` and `inputValue`.

This is not true. There's definitely a distinction. Maybe the distinction is a little fuzzy for the simple strings-only case, but most real-world scenarios are objects.

> Click on the field again - **A menu with all the options will be opened.** In downshift, the menu will only contain 1 item, the selected one.

This is also not true. Remember that downshift has 0 rendering responsibility. It's entirely up to you on how you want to render items. I just cooked this example up just for you: https://codesandbox.io/s/o5yk7pzmmy
It behaves exactly as you described you want it to behave, without any hacks. Amazing what happens when you give all rendering power to users right? :wink:

Let me know if this does not help resolve your issue and I can reopen this :)

**Comment by slavab89** [comment]
Amazing! 😎 you've just saved a bunch of code for me :)

btw, the other issue that i've opened partially does what i've written in the first commend. But the issue there is a bit different
