### ISSUE TITLE
Keep Downshift menu open always

### ISSUE THREAD

**Issue by areinmeyer** [paypal/downshift#193]
- `downshift` version: 1.6.0
I suspect this isn't a bug, but me not understanding how to properly avoid the state change.  If so, I'm happy to take the example below and submit it as an example or update any docs.

Problem:
I'd like to keep the Downshift menu open at all times, even after a selection event occurs as the Downshift component lives inside a Popup in my use case.  

I thought that by setting the `isOpen` value to true in the children render or updating the value in onStateChange that it would remain open. But once I select an item, it sets the isOpen to false and I'm not clear on how to prevent that.

Here's an example of what I'm trying to do.  
https://codesandbox.io/s/2wqqxxw6kj

Thanks for this component!

**Comment by tansongyang** [comment]
Closing because this appears to be an issue with the `Popup` component, not `downshift`. I don't know how it works, but I suspect that it's listening for clicks and closing itself if it receives one. With your current example, even mousing in, then mousing out of the popup causes it to disappear.

If you can replicate this issue with just downshift, we'll reopen.
