### ISSUE TITLE
onChange requires an event

### ISSUE THREAD

**Issue by oliverjam** [paypal/downshift#266]
- `downshift` version: 1.20.0
- `node` version: 8.5.0
- `npm` version: 5.5.1

Apologies if this is a stupid question, but I've been through all the examples and can't figure out what I'm doing wrong here 😭 

**What you did:**

We have a controlled input component that I'm trying to use with Downshift. The component accepts an `onChange` prop, which gets called with `event.target.value`. Usually we pass a Redux action here to control the input. We're not passing the entire event since every other input on the page just cares about the value.

**What happened:**

The problem is that Downshift's internal input change handler appears to require the event itself as the first argument. This means we get `Cannot read property 'value' of undefined at input_handleChange` as we aren't passing the entire event.

Am I doing something stupid or is this something I'll just have to work around by changing our input components to pass the entire event to their `onChange` handler?

Relevant code or config:

**Edit:** Here's a reduced test case Sandbox: https://codesandbox.io/s/23z0l5p24n

### The input
```jsx
class TextInput extends React.Component {
  ...
   handleChange(e) {
    const val = e.target.value;
    this.props.onChange(val);
  }
  ...
  render() {
    return <Input onChange={e => this.handleChange(e)} value={this.props.value} />
  }
}
```

### The autocomplete
```jsx
const Autocomplete = (props) => (
  <Downshift
    onChange={props.onChange}
    inputValue={props.value}
    render={({
      getInputProps,
      inputValue
      ...
      }) => <TextInput {...getInputProps()} />
        ...
  />
}
```

### Usage
```jsx
// connected to Redux store for value and onChange action
<Autocomplete
  ...
  value={props.checkout.country}
  onChange={selectedItem =>  props.updateFormDetails(selectedItem, "country")}
 />
```

**Comment by kentcdodds** [comment]
Hi @oliverjam,

The expectation is that you will apply the `getInputProps` to an `<input />` not your custom component. If that's not possible, then you can always just _not_ call `getInputProps` and instead apply the necessary props yourself. Here are the props that `getInputProps` applies:

https://github.com/paypal/downshift/blob/124885ad7bf9afe3db58b68ef85e45073261cd23/src/downshift.js#L612-L626

And the event handlers:

https://github.com/paypal/downshift/blob/124885ad7bf9afe3db58b68ef85e45073261cd23/src/downshift.js#L600-L611

Though now that I've thought about it, downshift doesn't expose the input event handlers. I'm not certain I want to do that... So as an alternative. you could reimplement the event handlers, or even better, your `TextInput` component could accept an `inputProps` prop which will be applied to the underlying input.

...

After considering this further, I've developed a solution that I think should work for you fairly nicely: https://codesandbox.io/s/n96zq9x36l

The basic idea is this:

```javascript
import React from 'react'

class Input extends React.Component {
  static defaultProps = {
    handleChange: e => {
      const val = e.target.value
      this.props.onChange(val)
    },
  }

  render() {
    const {value, handleChange, ...rest} = this.props
    return <input {...rest} value={value} onChange={e => handleChange(e)} />
  }
}

class DownshiftInput extends React.Component {
  handleChange = e => {
    this.props.onChange(e)
  }
  render() {
    return <Input {...this.props} handleChange={this.handleChange} />
  }
}

export {DownshiftInput}

export default Input
```

Then you'll use the `DownshiftInput` (which, quite honestly, is behaving as an input component should properly behave. It's best to provide the event to an `onChange` handler for elements like this) rather than the `Input` component. And the `Input` component can allow overrides to how `handleChange` behaves. Make sense?

In any case, I don't think this issue will result in a change in downshift so I'll go ahead and close this. Feel free to continue the conversation. Thanks!

**Comment by oliverjam** [comment]
Thanks for the detailed reply @kentcdodds! We ended up refactoring the underlying input to just always pass the event to the `onChange` handler. You're right, this makes more sense for an input
