### ISSUE TITLE
List automatically scrolled to the top after selecting item from the bottom of scrollable list

### ISSUE THREAD

**Issue by justynjozwiak** [paypal/downshift#286]
* `downshift` version: 1.22.3
* `node` version: 8.9.3
* `npm` (or `yarn`) version: 5.5.1

What you did: I have multiselect implemented (checkbox + label items), scrollable list, I selected the item from the bottom of scrollable list (`selectItem` method).

What happened: after selecting the item from the bottom of scrolled list, the list automatically scrolled to the top which is not intended behavior.

![downshift-jump](https://user-images.githubusercontent.com/7058669/34152699-cbaf2dac-e4af-11e7-8113-b8d9ab6748bc.gif)

Is there any way to prevent it? When I select item I want the scrollable dropdown list to stay at the same scrolled position.

**Comment by Paradox22** [comment]
My current solution for this involves adding an `index` property to each selectable item, controlling `highlightedIndex` and implementing a custom `onStateChange` handler. This looks fine, but it quickly gets out of hand with additional requirements like "reset `highlightedIndex` when input value is changed", "reset `highlightedIndex` when menu is toggled", "user can select up to N items" and so on.

My handler looks something like this (I did rip out a lot of additional code, so some special case might be missing):
```
  handleStateChange = (options) => {
    const stateChange = options;
    const selectedItem = stateChange.selectedItem;

    let nextState = {};
    let nextStateDirty = false;

    // Update highlightedIndex
    if (stateChange.hasOwnProperty("highlightedIndex")) {
      nextState.highlightedIndex = stateChange.highlightedIndex;
      nextStateDirty = true;
    }

    // Handle item selection
    if (selectedItem) {
      nextState.highlightedIndex = selectedItem.index;
      nextStateDirty = true;
    }

    if (nextStateDirty) {
      this.setState(nextState);
    }
  };
```

**Comment by kentcdodds** [comment]
Hmm... I feel like a well placed onClick handler with event.preventDefault() could help here.

Also, there was recently a release that may have fixed this 🤔 are you on the latest?

**Comment by jorrit91** [comment]
If anyone stumbles upon this issue.. we had the same issue with a multiselect implementation of Downshift. The problem was that we use the `onSelect` handler in `<Downshift />`. In this handler we _had_ to call the `openMenu` function to make sure the menu would stay open. But by doing that we actually reopened the menu everytime. 

This is how we fixed it:
- Remove `onSelect` from `<Downshift />` 
- Remove direct linking of the items by removing `{...getItemProps(...)}` from them
- Add a "manual" `onClick` handler to the children updating the internal state

Example code:

```
<Downshift
  itemToString={item => (item ? item.value : null)}
  selectedItem={null}
  onOuterClick={() => {
    onSelectItem(selected)
    setSearch('')
  }}
>
  <MenuList>
    {items.map((item, index) => (
        <li key={`item-${index}`}>
          <Checkbox
            onClick={() => {
              setSelected(state =>
                state.includes(item.value)
                  ? state.filter(i => i !== item.value)
                  : [...state, item.value]
              )
            }}
            id={item.value.toString()}
            label={item.label}
            value={item.value}
            checked={selected.includes(item.value)}
            readOnly
            mb={index === items.length - 1 ? 0 : '.5rem'}
          />
        </li>
      ))
    )}
  </MenuList>
</DownShift>
```

**Comment by asenmitrev** [comment]
For those using `useMultipleSelection` hooks with `useSelect`, the documentation currently describes overriding the state reducer of `useSelect`. A minor change to the supplied code will keep the scroll position and will not deselect the item:

```
            stateReducer: (state, actionAndChanges) => {
                const { changes, type } = actionAndChanges;
                switch (type) {
                    case useSelect.stateChangeTypes.MenuKeyDownEnter:
                    case useSelect.stateChangeTypes.MenuKeyDownSpaceButton:
                    case useSelect.stateChangeTypes.ItemClick:
                        return {
                            ...changes,
                            highlightedIndex: state.highlightedIndex, // Do not reset highlighted index
                            isOpen: true, // keep the menu open after selection.
                        };
                }
                return changes;
            },
```

**Comment by rburkovskyi** [comment]
For me it was (at least it seams so) auto focusing on search input element after you choose an element. Not sure what was causing it to focus, but since my search input is inside the menu itself on the top of the list, focusing was causing scroll to it. I just solved the problem by making search input sticky to top of the menu container.

**Comment by m0onspell** [comment]
For me it was (at least it seams so) auto focusing on search input element after you choose an element. Not sure what was causing it to focus, but since my search input is inside the menu itself on the top of the list, focusing was causing scroll to it. I just solved the problem by making search input sticky to top of the menu container.
