### ISSUE TITLE
rest() method does not fire the on input change events.

### ISSUE THREAD

**Issue by gotenxds** [paypal/downshift#288]
* `downshift` version: ^1.12.0
* `node` version:6.12.0
* `npm` (or `yarn`) version:3.10.10

What you did:
Called the reset method each time I change the selected value(s)

What happened:
The input events (onInput, onChange...) does not fire when `rest` changes the input value to `''`.

**Comment by kentcdodds** [comment]
Sorry @gotenxds, somehow I missed this (I was on vacation at the time you filed the issue, so I guess maybe that's why).

The `onInput`/`onChange` events respond to user input, and the `reset` function is programatically changing the value of the input, so it makes sense those event handlers would be called.

I'm sure there's another way to do what you want though. What are you trying to accomplish?

**Comment by krvajal** [comment]
Hi, I have the same issue here. In my case, I would like that when I clear the input field (value="") the `onStateChange` should be called and the menu closed.

```
export interface INameAutocompleteFieldProps {
  items: string[]
  value: string
  onChange: (selection: string) => void
}

const NameAutocompletField: React.StatelessComponent<INameAutocompleteFieldProps> = ({ items, onChange, value }) => (
  <Downshift
    defaultInputValue={value}
    selectedItem={value}
    onStateChange={({ inputValue }) => {
      console.log(inputValue)
      return inputValue && onChange(inputValue)
    }}
    onChange={onChange}
    render={({ getInputProps, getItemProps, getLabelProps, isOpen, inputValue, highlightedIndex, selectedItem }) => {
      const suggestedItems = items.filter(i => !inputValue || i.includes(inputValue))
      return (
        <div className={'inputContainer'}>
          <input
            {...getInputProps()}
            className={classnames('input', { opened: isOpen && suggestedItems.length > 0 })}
          />
          {isOpen ? (
            <div className={'searchSuggestions'}>
              {suggestedItems.map((item, index) => (
                <div
                  {...getItemProps({
                    key: item,
                    index,
                    item,
                    style: {
                      backgroundColor: highlightedIndex === index ? 'lightgray' : 'white',
                      fontWeight: selectedItem === item ? 'bold' : 'normal',
                      color: 'black',
                      padding: '10px',
                    },
                  })}>
                  {item}
                </div>
              ))}
            </div>
          ) : null}
        </div>
      )
    }}
  />
)
```
And the behavior I am seen is this 
![screen recording 2018-02-15 at 17 22](https://user-images.githubusercontent.com/5899385/36267746-f435718a-1274-11e8-9642-485f6e1e6d2d.gif)
Notice that when I clear the field the menu stays opened and the method `onStateChange` is not called.

**Comment by kentcdodds** [comment]
@krvajal, this is the default behavior by design. The idea is that when the user interacts with the input the menu should be open until the user moves on.

That said, in developing downshift I knew that not every use case would reflect my own, and so I've built in a few simple ways to change the built-in behavior. You could either use control props or a state reducer. I think the simplest here would be the state reducer.

Here's an example: https://codesandbox.io/s/yjq5vmznl9

And here's what the state reducer looks like:

```javascript
stateReducer={(state, changes) => {
  switch (changes.type) {
    case Downshift.stateChangeTypes.changeInput: {
      if (!changes.inputValue) {
        return {
          ...changes,
          isOpen: false,
        }
      }
    }
  }
  return changes
}}
```

I hope that makes sense! Good luck!

I'm going to go ahead and close this issue due to inactivity.
