### ISSUE TITLE
React.Fragment not allowed as returned renderProp

### ISSUE THREAD

**Issue by danseethaler** [paypal/downshift#305]
### Problem description:
The current setup doesn't support returning `React.Fragment` from the renderProp function. Instead it will reach [this line](https://github.com/paypal/downshift/blob/d9c830ee0075c68f9db8a3170a53f6be6c035c99/src/downshift.js#L891) which throws an error.

### Suggested solution:
From what I can tell the `isDOMElement` function in the [utils.js](https://github.com/paypal/downshift/blob/master/src/utils.js#L228) file should be updated to return true if the element is a React fragment. The function is currently returning `typeof element.type === 'string'` but in the case of a fragment the element type appears to be a symbol.

I'm happy to create a PR but wanted to have some discussion around it first.

**Comment by danseethaler** [comment]
Actually after looking into this more and exploring the `getRootProps` in the readme I'm thinking this may not be possible at all. I don't see any discussion about fragments so if anyone has any thoughts on it please enlighten me :)

**Comment by kentcdodds** [comment]
Hi Dan!

I can't think of a scenario where you'd want to use `<React.Fragment>` with downshift, but you should be able to do it with this:

```javascript
<Downshift render={downshift => (
  <React.Fragment>
    <div {...downshift.getRootProps({}, {suppressRefError: true})}>
      {/* this is where your stuff should go. Especially the items and input should be rendered here */}
    </div>
    <div>
      {/* other stuff can go here I guess... Not sure what you'd put here though... */}
    </div>
  </React.Fragment>
)} />
```

I don't think that I want to do any extra work to make it easier because it's hard for me to think of a use case where you'd not just simply use a `<div>` as the root.

Feel free to convince me otherwise, but I'll go ahead and close this for now :)

**Comment by danseethaler** [comment]
Thanks for the response Kent!

I tried the code here and it looks like it's throwing a different error `Uncaught TypeError: _this4._rootNode.contains is not a function at onMouseUp (downshift.esm.js:778)`.

I'm working on a component that is joined with other components to create a search bar so I was hoping to use a fragment - but at the end of the day you're right, a div will probably work just fine :)

**Comment by KumarAbhirup** [comment]
Having same problem, I need help. Using `div` completely breaks all my searchbox `styles`

**Comment by eriklharper** [comment]
A good reason to support fragments in general is when say using a composite component that you build with downshift, whose contents that you ultimately want to render to the DOM need to be direct flex children from a parent DOM node that applies `display: "flex"`.  When you include an extraneous root div, it breaks intended flex behavior because the nodes that you want to render inside a fragment are now wrapped inside another element.
