### ISSUE TITLE
Pressing [ENTER] on any input inside <form> element will toggle Downshift 

### ISSUE THREAD

**Issue by philipyoungg** [paypal/downshift#315]
* `downshift` version: 1.16.1
* `npm` (or `yarn`) version: npm 5.5.1

Relevant code or config

```javascript
const App = () => (
  <form>
    <input type='text'/>
    <Downshift>
      {({isOpen, getButtonProps}) => (
        <div>
          <button {...getButtonProps()}>
            ay
          </button>
          {isOpen &&
            <div>
              Yo wassup
            </div>
          }
        </div>
      )}
    </Downshift>
  </form>
);
```

What you did: Pressing [ENTER] on any input inside <form> element

What happened: It will toggle Downshift content 

What do I expect: It won't toggle the Downshift component when pressing [ENTER] inside form element.

Reproduction repository: https://codesandbox.io/s/pwn92r9plx

Suggested solution: I haven't checked on the "why" yet. Adding here first so I won't forget it. :)

**Comment by notruth** [comment]
@philipyoungg, It's not Downshift fault 🤨
https://codesandbox.io/s/wnm9zwqw0w

**Comment by notruth** [comment]
Pressing [ENTER] on any input element calls 'submit' event on form; If Button[type="submit"(by default)] is present in the form - before 'submit' event it will call 'click' event on this button.
[How to Fix](https://stackoverflow.com/questions/2825856/html-button-to-not-submit-form): <button **type="button"**>...</button> in your Form. 🤗

**Comment by philipyoungg** [comment]
Whoa didn’t know that before submit—form will click the button with type=submit. 

Thanks @notruth!

**Comment by philipyoungg** [comment]
Closing as this is not relevant anymore 😁

**Comment by kentcdodds** [comment]
My co-worker has this same problem. Maybe we should explicitly return the type as button from getButtonProps unless it's overridden. I don't think anyone would want the button to submit the form.

**Comment by philipyoungg** [comment]
@kentcdodds agreed.

**Comment by notruth** [comment]
Will it be appropriate to create a brunch with upcoming Button changes?
I also want to implement Button_focus() after [reset](https://github.com/paypal/downshift/blob/master/src/downshift.js#L296)

**Comment by kentcdodds** [comment]
> I also want to implement Button_focus() after reset

I don't think that's a common enough use case to make that the default. More common to want to focus the input I think...

Who wants to make a PR to add `type: 'button'` to this object?

https://github.com/paypal/downshift/blob/10c69241c9525b9866a42b9f9cbc7f76365bc0e6/src/downshift.js#L554-L561

**Comment by kentcdodds** [comment]
Actually, this is a great first-timers-only issue... So I'm going to prepare it later today and only allow first-time OSS contributors to submit a PR for it :)

**Comment by kentcdodds** [comment]
🆕🐥☝ First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

[About First Timers Only.](http://www.firsttimersonly.com/)

🤔 What you will need to know
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process.

📋 Step by Step
- [ ] 🙋 Claim this issue: Comment below (or assign yourself and continue at step 4 :)
Please 🙏 only claim if you want to start working on it within a day.
Once claimed we add you as contributor to this repository.
- [ ] 👌 Accept our invitation to this repository. Once accepted, assign yourself to this repository
- [ ] 👓 Please review our [Code of Conduct](https://github.com/paypal/downshift/blob/master/other/CODE_OF_CONDUCT.md)
In a nutshell: be patient and actively kind with us 😊
- [ ] 🔄 replace the available label with in progress.
- [ ] 📝 Update the file [`downshift.js`](https://github.com/paypal/downshift/blob/10c69241c9525b9866a42b9f9cbc7f76365bc0e6/src/downshift.js) in the this repo by following the steps in the [CONTRIBUTING.md](https://github.com/paypal/downshift/blob/10c69241c9525b9866a42b9f9cbc7f76365bc0e6/CONTRIBUTING.md) guide. Please add `type: 'button'` above [this line](https://github.com/paypal/downshift/blob/10c69241c9525b9866a42b9f9cbc7f76365bc0e6/src/downshift.js#L555).
- [ ] 🔀 Start a Pull Request. Include the text `closes #315` in the description.
If this is your first, welcome 🎉 😄 [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [ ] 🏁 Done 👍 Wait patiently for someone to review your PR and provide feedback :)

🤔❓ Questions? Comment here :)

**Comment by xutopia** [comment]
Hi, I would like to claim this issue please.

**Comment by kentcdodds** [comment]
Congratulations @xutopia!

**Comment by blueambr** [comment]
This is still an issue when using useSelect hook
