### ISSUE TITLE
itemToString returns null on react native 0.48.3

### ISSUE THREAD

**Issue by shaksi** [paypal/downshift#363]
* `downshift` version: 1.29.1
* `react native`: 0.48.3
* `node` version: 9.3.0
* `yarn` version: 1.3.2

Relevant code or config

https://snack.expo.io/BkVnOwpOM

What you did:
copied the sample code, and using it as a component.

What happened:
initially errors occured due to missing key.
add key to touchopacity in the component which fixed it (not sure if that is the best method)

![simulator screen shot - iphone 7 - 2018-03-07 at 13 13 01](https://user-images.githubusercontent.com/488328/37102791-8729a3d4-2220-11e8-88d5-2444f58d228c.png)

now i can search the cities with no problem but unfortunately the selection does not seem to work.

following the code it seems that itemToString is receiving a null variable. I dont understand why nor where i can start my search.

Reproduction repository:
https://snack.expo.io/BkVnOwpOM

**Comment by eliperkins** [comment]
> initially errors occured due to missing key.

Yup, the `key` is required here. When we add a proper example to the README, we should make sure that if you're using `map` instead of a `<FlatList>`, that the `key` is included.

> unfortunately the selection does not seem to work

Using your example, selecting a city seems to work just fine for me. Do you have more information on how to reproduce this?

> following the code it seems that itemToString is receiving a null variable. I dont understand why nor where i can start my search.

Can you capture a sequence of events that would repro this too?

**Comment by wKovacs64** [comment]
> Using your example, selecting a city seems to work just fine for me.

Same here, the city selection example works fine for me.

In my case, I tried [forking](https://snack.expo.io/rJrev3aOz) @donysukardi's [example](https://snack.expo.io/SJZm7qnOf) and replacing the `map` with a `FlatList`, which is what seemed to break things. `onChange` is no longer called, `selectedItem` is not updated, etc. and now this issue drew my attention to `itemToString`, which is indeed being called with `null` rather than the item (not sure if that's a symptom or the root cause, though).

FlatList Reproduction:
https://snack.expo.io/rJrev3aOz

**Comment by shaksi** [comment]
i was able to replicate my issue -  it seems to stem from having component inside the scrollview.

https://snack.expo.io/SyNu02adz

**Comment by wKovacs64** [comment]
`FlatList` inherits `ScrollView` props (most of the time), so `ScrollView` may be the culprit, ultimately? Eli said they are using `FlatList` successfully, though. 😕

**Comment by wKovacs64** [comment]
@eliperkins Do you know what you did differently that would enable `FlatList` to work for you vs. what @shaksi and I are doing? Our examples seem pretty vanilla. Thanks in advance.

**Comment by eliperkins** [comment]
In both of these examples, neither `ScrollView` has [`keyboardShouldPersistTaps`](https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps) set. This means that the `TextInput` will have focus/first responder, and not allow for `Touchable`s to be interacted with.

This worked with the `map` examples because no `ScrollView` was involved.

By adding `keyboardShouldPersistTaps="handled"` to your `ScrollView`s, you should be all set!

**Comment by wKovacs64** [comment]
Thanks!

**Comment by shaksi** [comment]
@eliperkins tried that, still not working - am I missing something simple. here is the updated snack: https://snack.expo.io/B1hEnc-KM

**Comment by wKovacs64** [comment]
@shaksi Props are case-sensitive, it should be `keyboardShouldPersistTaps`
