### ISSUE TITLE
Selecting an option after the items are filtered doesn't update selectedItem

### ISSUE THREAD

**Issue by peterph-am** [paypal/downshift#371]
* `downshift` version: 1.3.0

When you click on an item after it has been filtered nothing happens, the `selectItem` callback isn't fired.

Shouldn't the selectedItem change to the item clicked even after filtering the items?

This happens in the type ahead example online also: https://codesandbox.io/s/82m2px40q9

**Comment by austintackaberry** [comment]
I believe the `onSelect` prop gets called when you click an item if you update to the latest version of downshift, 1.30.0. Perhaps we should update the version on that codesandbox.

**Comment by kentcdodds** [comment]
The reason `onChange` isn't being fired is because that example updates the selected item as you type. So if you've typed out the entire item string ("apple" for example), then the selected item will be "apple" and when you click on the item in the list "apple" then the selected item doesn't change. It stays the same. This is why `onChange` doesn't fire... Because the selection didn't change.

As @austintackaberry suggested (thanks Austin!), in the latest version of downshift there's an `onSelect` which will fire regardless of whether the selection was changed: https://codesandbox.io/s/wypzn2nv7k

Good luck!
