### ISSUE TITLE
Add documentation about getButtonProps applying type: 'button' by default

### ISSUE THREAD

**Issue by arthurdenner** [paypal/downshift#496]
- `downshift` version: 2.0.10
- `node` version: 9.11.1
- `npm` (or `yarn`) version: 1.7.0

**Relevant code or config**
N/A

**Problem description**:
I was trying to toggle Downshift when submitting a form by pressing Enter in an input, thinking that the form would submit (normal behaviour), but it didn't. Looking at #315 I saw why and "fixed" it (because the current behaviour makes more sense). However, maybe we should document it?

**Suggested solution**:
We could add a simple note such as below:

> Note that `getButtonProps` applies `type: 'button'` by default, so make sure to pass `type: 'submit'` to this control prop if you want to have the normal behaviour of a button inside a form.

**Comment by stipsan** [comment]
Hey! 😄 Could you share something on [codesandbox](https://codesandbox.io/s/6z67jvklw3) to help understand the use case?

**Comment by arthurdenner** [comment]
Hey @stipsan, here it is: https://codesandbox.io/s/ko0w1ro537

Trying to explain better, I'd expect these two codes to work equally, but since #315 it doesn't because `getButtonProps` applies `type: 'button'` by default. If you uncomment the line 32, `With Downshift` works like `Without Downshift`, so I'm suggesting adding a note about it.

**Comment by kentcdodds** [comment]
You should not be using that prop getter for a button you want to use as a submit button though. Maybe I'm missing something...

**Comment by stipsan** [comment]
Thanks for sharing the example, it makes it more clear what you mean 😄 

Have you considered customizing the submit event that is currently calling `e.preventDefault()` and use the `openMenu` prop in there to open downshift? In my experience relying on how browsers deal with onClick on submit buttons when hitting enter on text inputs can be really flaky between browsers. It can also make the code harder to maintain since the logic flow rely on behaviors that are implicit 😅

**Comment by arthurdenner** [comment]
I totally missed that `openMenu` prop, thanks for pointing it out, @stipsan.

By using that, I can accomplish the same behavior with a more correct code.

Thank you both!
