### ISSUE TITLE
onFocus support

### ISSUE THREAD

**Issue by martinmckenna** [paypal/downshift#504]
**Problem description**:
When using the `downshiftStateReducer`, I'd like to be able to add a switch case for input focus

**Comment by kentcdodds** [comment]
The reason that there isn't any support in the state reducer is because no state change occurs on input focus. If you want to respond to focus of the input then you can apply `onFocus` to your input like so:

```javascript
<input {...getInputProps({onFocus: () => console.log('on focus')})} />
```

Good luck!

**Comment by martinmckenna** [comment]
@kentcdodds The problem that I was running into was the fact that (when in use with React), the `onFocus` handler was not triggering a render on Downshift's internal render method.

I need a way to change state onFocus and trigger the contents inside Downshift's render method to run

**Comment by kentcdodds** [comment]
What specifically do you need to have happen?

**Comment by kentcdodds** [comment]
Could you simply use: `getInputProps({onFocus: openMenu})`? The `openMenu` helper is documented in the README (sorry, short on time otherwise I'd make an example for you).

**Comment by martinmckenna** [comment]
@kentcdodds ah! yep that works like a charm. Thanks!

Definitely would help to have examples of using the action helpers in the README if you're taking requests for enhancements

**Comment by kentcdodds** [comment]
Here it is: https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fother-examples%2Fusing-actions.js&moduleview=1

**Comment by danielrvt** [comment]
@kentcdodds you make this lib fun to use, thanks!

**Comment by kentcdodds** [comment]
Thanks 😊

**Comment by constantinpojoga** [comment]
> Could you simply use: `getInputProps({onFocus: openMenu})`? The `openMenu` helper is documented in the README (sorry, short on time otherwise I'd make an example for you).

@kentcdodds, Thanks for the great library!!! Regarding your solution, I was fighting with it for a while. The issue with it is that on input focus, the `onFocus` will trigger as expected and the `openMenu` will do the job. The issue comes after clicking an option since the `onFocus` will fire one more time, it will call `openMenu` one more time, and `onInputValueChange` will not fire. Not sure if you wanna fire that onFocus 2 times on purpose, (which may be related to accessibility) or I need to open a bug for it.

Related to this issue, this did the job for me, (opening only if !isOpen):
`onFocus: e => {
              if (!e.target.value) {
                if (!isOpen) {
                  openMenu();
                }
              } else {
                e.target.select();
              }
            },`

**Comment by meotimdihia** [comment]
@kentcdodds : I have the problem is like as @constantinpojoga . I can re-create it on the example: 
https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/hooks/useCombobox/algolia-instantsearch/index.js

You can check the modified source code is forked:  
https://codesandbox.io/s/gifted-morning-h9gbf

**Comment by knoefel** [comment]
@meotimdihia @constantinpojoga @silviuaavram I'm experiencing the same problem. Is the solution from @constantinpojoga the only option? Thx in advance!
