### ISSUE TITLE
Investigate intermittent TypeScript test failures

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#547]
If you take a look at the [Travis Build history](https://travis-ci.org/paypal/downshift/builds) ([especially PRs](https://travis-ci.org/paypal/downshift/pull_requests)), you'll notice a fair number of failures. These are due to the `test:ts` script failing. I have no idea what's going on. This is the only output:

```
[test:ts] Killed
[test:ts] npm run test:ts --silent exited with code 137
```

Help is appreciated :) This is slowing our releases. I normally just rerun it until it starts working.

**Comment by stipsan** [comment]
Interesting. I've never seen that error thrown by TS. But I have seen failures on Travis before with exit code 137 that happened due to a child_process running out of memory. Could that be happening here?

Time to play with this shiny new [ndb](https://github.com/GoogleChromeLabs/ndb) thing me thinks 🙂

**Comment by kentcdodds** [comment]
It could definitely be a memory problem. We're running several scripts in parallel and perhaps it's too many for Travis to handle. Maybe we should split them into two on Travis. We could do this in the travis config:

```
script:
  - kcd-scripts validate lint,build-and-test,test:cover,test:ts
  - kcd-scripts validate test:flow:coverage,test:ssr,test:cypress
```
