### ISSUE TITLE
The "blurInput" state change type is not emmited if the user clicked outside the input

### ISSUE THREAD

**Issue by MeLlamoPablo** [paypal/downshift#640]
- `downshift` version: *2.0.20*
- `node` version: *not applicable (codesandbox)*
- `npm` (or `yarn`) version: *not applicable (codesandbox)*

**Relevant code or config**

```javascript
import React from "react";
import { render } from "react-dom";
import Downshift from "downshift";

const items = [
  { value: "apple" },
  { value: "pear" },
  { value: "orange" },
  { value: "grape" },
  { value: "banana" }
];

function stateReducer(state, changes) {
  console.log({ state, changes });
  switch (changes.type) {
    case Downshift.stateChangeTypes.blurInput:
      alert("Input blurred (Downshift)");
      return { ...state, ...changes };
    default:
      return { ...state, ...changes };
  }
}

function handleInputRefObtained(ref) {
  if (ref) {
    ref.addEventListener("blur", () => alert("Input blurred (DOM)"));
  }
}

render(
  <Downshift
    onChange={selection => alert(`You selected ${selection.value}`)}
    itemToString={item => (item ? item.value : "")}
    stateReducer={stateReducer}
  >
    {({
      getInputProps,
      getItemProps,
      getLabelProps,
      isOpen,
      inputValue,
      highlightedIndex,
      selectedItem
    }) => (
      <div>
        <label {...getLabelProps()}>Enter a fruit</label>
        <input {...getInputProps()} ref={handleInputRefObtained} />
        {isOpen ? (
          <div>
            {items
              .filter(item => !inputValue || item.value.includes(inputValue))
              .map((item, index) => (
                <div
                  {...getItemProps({
                    key: item.value,
                    index,
                    item,
                    style: {
                      backgroundColor:
                        highlightedIndex === index ? "lightgray" : "white",
                      fontWeight: selectedItem === item ? "bold" : "normal"
                    }
                  })}
                >
                  {item.value}
                </div>
              ))}
          </div>
        ) : null}
      </div>
    )}
  </Downshift>,
  document.getElementById("root")
);
```

**What you did**:

Expect the `onStateChange` to emit the `Downshift.stateChangeTypes.blurInput` change type when the input is blurred **by clicking on other HTML Element instead of pressing tab**.

**What happened**:

This expectation was not met.

**Reproduction repository**:

[![Edit simple downshift 🏎 example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jply93jvmw)

**Problem description**:

Currently, in our application, we must obtain a reference to the input being used in Downshift and manually handle the `blur` event. Ideally, we would only use `Downshift.stateChangeTypes.blurInput`, however, this does not work when clicking outside an element.

In order to reproduce, go to the code sandbox, type a value, and then press tab. You should see two alerts, one indicating that the DOM event listener has correctly received the event, and other indicating that the state change listener has also received it.

However, if you focus the input, type a value, then click on the label, you should only see the alert indicating that the DOM event listener received the event. You should not see the alert triggered by the state change listener.

**Suggested solution**:

Make `onStateChange` emit blur events that are caused by clicking outside the input.

Thank you for your help!

**Comment by kentcdodds** [comment]
Hi @MeLlamoPablo,

The problem is that if we did that, then the menu would disappear between the time the blur event fires and the click event fires. This means that users wouldn't be able to click elements in the menu.

Believe me, I've dealt with that bug many times. Really annoying.

So downshift handles this for you by not firing the blur event on mouse down. Instead, it waits until there's a mouse up, at which point it determines where the click happened and resets the state if it was outside downshift.

This does make things a little more complicated and there's a way to work around this by using one of the other state change types or the `onOuterClick` prop. However, these will _only_ run when there is state that needs to change. If you need to be notified whenever the input is blurred, then you can just pass `onBlur` to `getInputProps`.

Is there a reason that wont work for you? Your example is a little contrived. I could help you if you describe what you're really trying to accomplish.

**Comment by kentcdodds** [comment]
> prevents you from subscribing to the Downshift.stateChangeTypes.blurInput event 

I think this is the main confusion. The `stateReducer` isn't an "event dispatch handler" but a "state change handler." So the "events" are actually state changes. If any particular event does not cause a state change, then your `stateReducer` will not be called. In addition to that, your `stateReducer` should be a pure function so it would be wrong if you're doing anything other than handling state changes and returning your modifications to those state changes.

> I think that the blurInput name should be changed 

Due to the nature of `onStateChange` and `stateReducer`, the name will not be changed. The `type` refers to what caused the state change. It will not be called whenever the event happens. I think it's pretty clear that if you want to handle an event you can do so as you normally would through the prop getters. I'm not sure how to improve the docs to emphasize this. PRs welcome though.

> Obviously, the definition of "hack" is relative, but using onBlur feels like a hack to me when we could use an event provided by downshift instead. And I'd argue that no library should force their users to do something that "feels like a hack".

I think you're thinking about downshift all wrong. The beauty of downshift is how little it does for you. You are responsible for rendering the input, so interacting with that input as you would without downshift is a feature.

So no, we wont be adding state change types for things that don't actually change any state (we do already have a `mouseUp` state change type, but again, those are only called when state actually changes).

I'll add a note to the README calling out the fact that your `onStateChange` and `stateReducer` will only be called when state actually changes.

Thanks!

**Comment by MeLlamoPablo** [comment]
@kentcdodds thank you for your insights!
