### ISSUE TITLE
Use refs for items in place of data-attributes

### ISSUE THREAD

**Issue by souporserious** [paypal/downshift#81]
Now that we have a way to do this for the root element, how do you feel about taking the same approach for items and allow them to accept a `refKey`? I imagine there is a small perf win here since we would have access to the node and not have to query it.

**Comment by kentcdodds** [comment]
Actually, I think the perf win would be in _not_ using `ref` (because the `ref` function is called once for every item on every render). Also, I don't like `refKey` because it's an implementation detail thing. If I switch from a regular dom element to a glamorous component, now I have to update the `refKey`. I don't have to think about that today. So unless we find a compelling reason to reduce the DX in this case, I want to keep things as they are with `data-` attributes :+1:

**Comment by souporserious** [comment]
Sounds good 👍
